/*
 * Dispatcher.cpp
 *
 *  Created on: 05.05.2025
 *      Author: Thomas
 */

#include "Dispatcher.h"
#include "Action.h"
#include "Data.h"
#include "DispatcherEvents.h"
#include "Context.h"
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/dispatch.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
#include <unistd.h>

#define GNS_NAME "Dispatcher"
#define NUMBER_OF_COMPONENTS 4

Dispatcher::Dispatcher() {
	//system("gns -s ");	 //for FBM_1
	//system("gns -c "); //for FBM_2
	data = new Data();
	action = new Action(data);
	context = new Context(action, data);

}

Dispatcher::~Dispatcher() {
	delete context;
	delete action;
	delete data;

}

int Dispatcher::handle_pulse_msg(header_t header,int rcvid){
	if ((_PULSE_CODE_MINAVAIL <= header.code) && (header.code <= _PULSE_CODE_MAXAVAIL)){
			handle_appl_pulse(header, rcvid);
		} else {
			handle_QNX_pulse(header, rcvid);
		}
}

int Dispatcher::handle_appl_pulse(header_t header,int rcvid){
	switch (header.code) {
	case FSM_READY:
		context->fsm_ready();
		break;
	case HAL_READY:
		context->hal_ready();
		break;
	case MQTT_READY:
		context->mqtt_ready();
		break;
	case QNET_READY:
		context->qnet_ready();
		break;
	case FSM_NOT_READY:
		context->fsm_not_ready();
		break;
	case HAL_NOT_READY:
		context->hal_not_ready();
		break;
	case MQTT_NOT_READY:
		context->mqtt_not_ready();
		break;
	case QNET_NOT_READY:
		context->qnet_not_ready();
		break;
	case DISPATCHER_READY:
		context->dispatcher_ready();
		break;
	default:
		context->dispatch_message();
	}
}


int Dispatcher::handle_QNX_pulse(header_t header,int rcvid){
	switch (header.code) {
		case _PULSE_CODE_DISCONNECT:
			printf("Dispatcher _PULSE_CODE_DISCONNECT\n");
/* A client disconnected all its connections (called
* name_close() for each name_open() of our name) or
* terminated. */
			ConnectDetach(header.scoid);
			break;
		case _PULSE_CODE_UNBLOCK:
			printf("Dispatcher received _PULSE_CODE_UNBLOCK\n");
/* REPLY blocked client wants to unblock (was hit by
* a signal or timed out). It's up to you if you
* reply now or later. */
			break;
		default:
/* A pulse sent by the kernel like
* _PULSE_CODE_COIDDEATH or _PULSE_CODE_THREADDEATH
* from the kernel? */
			printf("Dispatcher received some other QNX pulse msg.\n");
			break;
	}
}

int Dispatcher::handle_QNX_IO_msg(header_t header, int rcvid){
	switch (header.code) {
			case _PULSE_CODE_DISCONNECT:
				printf("Dispatcher _PULSE_CODE_DISCONNECT\n");
	/* A client disconnected all its connections (called
	* name_close() for each name_open() of our name) or
	* terminated. */
				ConnectDetach(header.scoid);
				break;
			case _PULSE_CODE_UNBLOCK:
				printf("Dispatcher received _PULSE_CODE_UNBLOCK\n");
	/* REPLY blocked client wants to unblock (was hit by
	* a signal or timed out). It's up to you if you
	* reply now or later. */
				break;
			case 12:
				MsgReply( rcvid, EOK, NULL, 0 );
				break;
			default:
	/* A pulse sent by the kernel like
	* _PULSE_CODE_COIDDEATH or _PULSE_CODE_THREADDEATH
	* from the kernel? */
				printf("Dispatcher received some other QNX pulse msg: %d\n",header.code);
				break;
		}
}

int Dispatcher::handle_app_msg(header_t header,int rcvid){
	printf("Receiver: Unexpected message type 0x%04X\n", header.type);
	MsgError(rcvid,EPERM);
}

int Dispatcher::start_dispatcher() {
	name_attach_t *attach;
	attach = name_attach(NULL, GNS_NAME, NAME_FLAG_ATTACH_GLOBAL);
	if ( attach == NULL) {
		perror("Dispatcher: name_attach failed");
		return EXIT_FAILURE;
	}

	printf("Dispatcher: name_attach successful\n");
	while (1) {
	// Waiting for a message and read first header
		header_t header;
		int rcvid = MsgReceive (attach->chid, &header, sizeof (header_t), NULL);
		if (rcvid == -1) { // Error occurred
			perror("Dispatcher: MsgReceived failed");
			continue;
		}
		if (rcvid == 0) {// Pulse was received
			this->handle_pulse_msg(header, rcvid);
			continue;
		}
		// some sync msg was received
		if ((_IO_BASE <= header.type) && (header.type <= _IO_MAX)) {
			// Some QNX IO msg generated by gns was received
			handle_QNX_IO_msg(header, rcvid);
			continue;
		}
		// A sync msg (presumable ours) was received; handle it
		handle_app_msg(header, rcvid);
	}
	// Server stopped; remove the name from the space
	name_detach(attach, 0);
	return EXIT_SUCCESS;
}

