/*
 * Server.cpp
 *
 *      Author: lucas
 */


#include "Server.h"
#include <iostream>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/dispatch.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/types.h>
#include <unistd.h>

//using namespace SC;

//void Server::do_something(){
//	std::cout << "Hello World" << std::endl;
//}

int Server::sender() { // Sender side of the code
	int receiver_coid;
// Use GNS for setting up the connection to the server
// - running somewhere in the network
	receiver_coid = name_open(Attach_Point, NAME_FLAG_ATTACH_GLOBAL);
	if (-1 == receiver_coid){
		perror("sender: name_open failed");
		return EXIT_FAILURE;
	}
// Send some pulse messages to receiver
	for (int no = 0; no < NO_OF_MSGS; no++) {
		printf("Sender sends pulse msg (code,value) = (%d,%d)\n", MY_PULSE_CODE, no);
		MsgSendPulse(receiver_coid, SIGEV_PULSE_PRIO_INHERIT, MY_PULSE_CODE, no);
		sleep(2);
	}
	name_close(receiver_coid); // close connection
	return EXIT_SUCCESS;
}

void Server::handle_QNX_pulse(header_t hdr, int rcvid){
	switch (hdr.code) {
		case _PULSE_CODE_DISCONNECT:
			printf("Received _PULSE_CODE_DISCONNECT\n");
/* A client disconnected all its connections (called
* name_close() for each name_open() of our name) or
* terminated. */
			ConnectDetach(hdr.scoid);
			break;
		case _PULSE_CODE_UNBLOCK:
			printf("Server received _PULSE_CODE_UNBLOCK\n");
/* REPLY blocked client wants to unblock (was hit by
* a signal or timed out). It's up to you if you
* reply now or later. */
			break;
		default:
/* A pulse sent by the kernel like
* _PULSE_CODE_COIDDEATH or _PULSE_CODE_THREADDEATH
* from the kernel? */
			printf("Receiver received some other QNX pulse msg.\n");
			break;
	}
}

void Server::handle_appl_pulse(header_t hdr, int rcvid){
	switch (hdr.code) {
	case MY_PULSE_CODE:
		printf("MY_PULSE_CODE with data = %d received\n", hdr.value.sival_int);
		break;
	default:
/* A pulse sent by one of your processes? */
		printf("Receiver received some other appl. pulse msg.\n");
		break;
	}
}

void Server::handle_pulse(header_t hdr, int rcvid){
	if ((_PULSE_CODE_MINAVAIL <= hdr.code) && (hdr.code <= _PULSE_CODE_MAXAVAIL)){
		handle_appl_pulse(hdr, rcvid);
	} else {
		handle_QNX_pulse(hdr, rcvid);
	}
}

void Server::handle_ONX_IO_msg(header_t hdr, int rcvid){
	if (hdr.type == _IO_CONNECT ) {
// QNX IO msg _IO_CONNECT was received; answer with EOK
		printf("Server received _IO_CONNECT (sync. msg) \n");
		MsgReply( rcvid, EOK, NULL, 0 );
		return;
	}
// Some other QNX IO message was received; reject it
	printf("Server received unexpected (sync.) msg type = 0x%04X\n", hdr.type);
	MsgError( rcvid, ENOSYS );
}

void Server::handle_app_msg(header_t hdr, int rcvid){
	printf("Receiver: Unexpected message type 0x%04X\n", hdr.type);
	MsgError(rcvid,EPERM);
}

int Server::receiver() { // Receiver side of the code
	name_attach_t *attach;
// Create a global name (/dev/name/global/...) known within the network
	attach = name_attach(NULL, Attach_Point, NAME_FLAG_ATTACH_GLOBAL);
	if ( attach == NULL) {
		perror("Server: name_attach failed");
		return EXIT_FAILURE;
	}
	printf("Server: name_attach succesfull\n");
	while (1) {
		// Waiting for a message and read first header
		header_t header;
		int rcvid = MsgReceive (attach->chid, &header, sizeof (header_t), NULL);
		if (rcvid == -1) { // Error occurred
			perror("Server: MsgReceived failed");
			break;
		}
		if (rcvid == 0) {// Pulse was received
			handle_pulse(header, rcvid);
			continue;
		}
// some sync msg was received
		if ((_IO_BASE <= header.type) && (header.type <= _IO_MAX)) {
// Some QNX IO msg generated by gns was received
			handle_ONX_IO_msg(header, rcvid);
			continue;
		}
// A sync msg (presumable ours) was received; handle it
		handle_app_msg(header, rcvid);
	}
// Server stopped; remove the name from the space
	name_detach(attach, 0);
	return EXIT_SUCCESS;
}

int Server::qnet_init(int argc,const char argv) {
	if (argc < 2) {
		printf("Usage %s -s | -r \n", argv);
		return EXIT_FAILURE;
	} else if (argv == 's') {
		printf("Running Sender ... \n");
		return sender(); /* see name_open() for this code */
	} else if (argv == 'r') {
		printf("Running Receiver ... \n");
		return receiver(); /* see name_attach() for this code */
	} else {
		printf("Usage %s -s | -c \n", argv);
		return EXIT_FAILURE;
	}
}
