/*
 * DispatcherEvents.h
 *
 *  Created on: 12.05.2025
 *      Author: User
 */

#ifndef SRC_DISPATCHER_HDR_DISPATCHEREVENTS_H_
#define SRC_DISPATCHER_HDR_DISPATCHEREVENTS_H_

#define DISPATCHER_ONLINE 1
#define FSM_READY 2
#define HAL_READY 3
#define MQTT_READY 4
#define QNET_READY 5
#define FSM_NOT_READY 7
#define HAL_NOT_READY 8
#define MQTT_NOT_READY 9
#define QNET_NOT_READY 10
#define DISPATCHER_READY 11
#define TESTEVENT 12




#endif /* SRC_DISPATCHER_HDR_DISPATCHEREVENTS_H_ */
