#ifndef EVENT_H
#define EVENT_H
#pragma once

#define OPEN_GATE_SLOW_DURATION 1750
#define OPEN_GATE_FAST_DURATION 1000
#define PUSH_DURATION 500

#include <cstdint>

enum class InterruptEnum : int
{
    LASER_FRONT_BLOCKED = 1, // the rest will continue (-2, -3)
    LASER_FRONT_UNBLOCKED,
    LASER_BACK_BLOCKED,
    LASER_BACK_UNBLOCKED,
    BUTTON_START_PRESSED,
    BUTTON_START_RELEASED,
    BUTTON_STOP_PRESSED,
    BUTTON_STOP_RELEASED,
    BUTTON_RESET_PRESSED,
    BUTTON_RESET_RELEASED,
    BUTTON_ESTOP_PRESSED,
    BUTTON_ESTOP_RELEASED,
    METAL_DETECTED,
    METAL_NOT_DETECTED,
    LASER_SORTING_GATE_BLOCKED,
    LASER_SORTING_GATE_UNBLOCKED,
    LASER_RAMP_BLOCKED,
    LASER_RAMP_UNBLOCKED,
    ADC_TOP_AREA_BLOCKED,
    ADC_TOP_AREA_UNBLOCKED,
    ADC_SIDE_AREA_BLOCKED,
    ADC_SIDE_AREA_UNBLOCKED,
    IS_SWITCH,
    IS_PUSHER
};
enum class ActuatorEnum : int
{
    MOTOR_RIGHT_START = 1,
    MOTOR_LEFT_START,
    MOTOR_SLOW_ON,
    MOTOR_SLOW_OFF,
    MOTOR_STOP,
    SORTING_ON,
    SORTING_OFF,
    TRAFFIC_GREEN_ON_SLOW,
    TRAFFIC_GREEN_ON_FAST,
    TRAFFIC_YELLOW_ON_SLOW,
    TRAFFIC_YELLOW_ON_FAST,
    TRAFFIC_RED_ON_SLOW,
    TRAFFIC_RED_ON_FAST,
    TRAFFIC_GREEN_ON,
    TRAFFIC_GREEN_OFF,
    TRAFFIC_RED_ON,
    TRAFFIC_RED_OFF,
    TRAFFIC_YELLOW_ON,
    TRAFFIC_YELLOW_OFF,
    LED_START_ON,
    LED_START_OFF,
    LED_RESET_ON,
    LED_RESET_OFF,
    LED_Q1_ON,
    LED_Q1_OFF,
    LED_Q2_ON,
    LED_Q2_OFF
};

enum class Topic : int8_t
{
    INTERRUPT = 1,
    ACTUATOR,
    COM,
    ADC,
    STOP_THREAD,
    TIMER,
    INTERNAL
};

enum class ADC_Enum : int
{
    ADC_WH_DETECT = 0xFFA0,
    ADC_WF_DETECT,
    ADC_W_B_DETECT,
    ADC_W_NOT_DETECT,
    ADC_CALIBRATE,
    ADC_MESURE,
    ADC_INVALID_MESURE,
    ADC_CALIBRATION_DONE,
    ADC_STOP,
    ADC_RESET,
    ADC_NEW_PIECE
};

enum class COM_Enum : int
{
    NEW_PIECE_TO_SORT = 1,
    NEW_PIECE_NOT_TO_SORT,
    BUTTON_ESTOP_PRESSED,
    BUTTON_ESTOP_RELEASED,
    HEARTBEAT,
    TIMEOUT_COM,
    RECONNECT,
    RAMP_FULL,
    RAMP_NOT_FULL,
    RESET_TO_FLAT,
    RESET_TO_TALL,
    RESET_TO_TALL_W_METAL,
    FBM_2_READY,
    FBM_2_BUSY,
    REQUEST_TRANSFER,
    TRANSFER_DONE,
    TRANSFER_FAILED,
    TRANSFER_START_TALL,
    TRANSFER_START_TALL_W_METAL,
    TRANSFER_START_FLAT,
    TRANSFER_START_OTHER
};

enum class Internal_Enum : int
{
    SORT_OUT = 1,
    SORT_OUT_FBM2,
    LET_THROUGH,
    CHECK_PIECE,
    RESET_TO_FLAT,
    RESET_TO_TALL,
    RESET_TO_TALL_W_METAL
};

enum class TIMER_ID : int
{
    WAITING_IM = 1,
    OPENGATE_CDS,
    OPENGATE_LPT,
    PUSHRAMP_STR,
    CAL_GATE_RAMP2,
    CAL_GATE_RAMP1
};

#endif
